# Generated by Django 4.1.5 on 2023-02-17 14:37

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publishing_house',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishing_house', models.TextField(verbose_name='Издательство')),
            ],
            options={
                'verbose_name': 'Издательство',
                'verbose_name_plural': 'Издательства',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique_with=('author',))),
                ('author', models.CharField(max_length=255, verbose_name='Автор(ы)')),
                ('author_description', models.TextField(verbose_name='Описание автора / издательства')),
                ('photo', models.ImageField(upload_to='books_photos', verbose_name='Фотография')),
                ('publishing_house', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='books.publishing_house', verbose_name='Издательство')),
            ],
            options={
                'verbose_name': 'Книги',
                'verbose_name_plural': 'Книги',
                'ordering': ['-id'],
            },
        ),
    ]
