# Generated by Django 4.1.5 on 2023-02-18 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author_description_en',
            field=models.TextField(null=True, verbose_name="Author's description | Описание автора"),
        ),
        migrations.AddField(
            model_name='books',
            name='author_description_ru',
            field=models.TextField(null=True, verbose_name="Author's description | Описание автора"),
        ),
        migrations.AddField(
            model_name='books',
            name='author_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Author(s) | Автор(ы)'),
        ),
        migrations.AddField(
            model_name='books',
            name='author_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Author(s) | Автор(ы)'),
        ),
        migrations.AddField(
            model_name='books',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name | Название'),
        ),
        migrations.AddField(
            model_name='books',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Name | Название'),
        ),
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(max_length=255, verbose_name='Author(s) | Автор(ы)'),
        ),
        migrations.AlterField(
            model_name='books',
            name='author_description',
            field=models.TextField(verbose_name="Author's description | Описание автора"),
        ),
        migrations.AlterField(
            model_name='books',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name | Название'),
        ),
        migrations.AlterField(
            model_name='books',
            name='photo',
            field=models.ImageField(upload_to='books_photos', verbose_name='Photo | Фотография'),
        ),
        migrations.AlterField(
            model_name='books',
            name='publishing_house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='books.publishing_house', verbose_name='Publishing house | Издательство'),
        ),
    ]
